defaults:
  - encoder: light
  - encoder_gnova: light
  - decoder: light
  - decoder_gnova: light
  - train: train
  - infer: optimal_path_inference
  - sample: 4090_24g_light
  - embedding: embedding
  - data: data
  - _self_

mode: train
task: node_classification
train_spec_header_path: None
eval_spec_header_path: None
train_dataset_dir: None
eval_dataset_dir: None
serialized_model_path: None
device: gpu
server: bsi
gnova_file_name: GNova-Multi-DIA_pretrain-2loss-debug-gradaccu100-largelr

wandb:
  entity: winston-zheng-m
  project: RNova-DIA
  name: Zeping-Encoder
